#!/usr/bin/env python3

import errno
import json
import os
import socket
import sys

import agent


def is_port_in_use(port: int) -> bool:
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind(("", port))
        sock.close()
        sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        sock.bind(("", port))
        sock.close()
    except OSError as ex:
        if ex.errno != errno.EADDRINUSE:
            raise
        return True
    return False


data = json.load(sys.stdin)
username = data["username"]
password = data["password"]
http_port = data["http_port"]

secrets_env = {
    "COPYPARTY_USERNAME": username,
    "COPYPARTY_PASSWORD": password,
}
agent.write_envfile("secrets.env", secrets_env)

ports_in_use = []
if str(http_port) != os.environ.get("HTTP_PORT", "") and is_port_in_use(http_port):
    ports_in_use.append(http_port)

if ports_in_use:
    print(f"Following port/s are already in use: {ports_in_use}", file=sys.stderr)
    sys.exit(1)

agent.set_env("HTTP_PORT", http_port)
