#!/usr/bin/env python3

import os

import agent

ports = []
ports.append(os.environ["HTTP_PORT"] + "/tcp")

agent.remove_public_service(os.environ["MODULE_ID"])
agent.add_public_service(os.environ["MODULE_ID"], ports)
