#!/usr/bin/env python3

import json
import os
import sys

import agent

config = {}
config["username"] = agent.read_envfile("secrets.env")["COPYPARTY_USERNAME"] if os.path.exists("secrets.env") else None
config["password"] = agent.read_envfile("secrets.env")["COPYPARTY_PASSWORD"] if os.path.exists("secrets.env") else None
config["http_port"] = int(os.environ.get("HTTP_PORT", ""))
json.dump(config, fp=sys.stdout)

