#!/usr/bin/env python3

import json
import os
import sys

import agent

config = {}
config["username"] = agent.read_envfile("secrets.env")["COPYPARTY_USERNAME"] if os.path.exists("secrets.env") else None
config["password"] = agent.read_envfile("secrets.env")["COPYPARTY_PASSWORD"] if os.path.exists("secrets.env") else None
config["host"] =  os.getenv("TRAEFIK_HOST")
config["http2https"] =  os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] =  os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

json.dump(config, fp=sys.stdout)

