#!/usr/bin/env python3
import json
import os
import sys

import agent

data = json.load(sys.stdin)
environment = data["environment"]

configure_retval = agent.tasks.run(
    agent_id=os.environ["AGENT_ID"],
    action="configure-module",
    data={
        "username": agent.read_envfile("secrets.env")["COPYPARTY_USERNAME"] if os.path.exists("secrets.env") else None,
        "password": agent.read_envfile("secrets.env")["COPYPARTY_PASSWORD"] if os.path.exists("secrets.env") else None,
        "host": environment["TRAEFIK_HOST"],
        "http2https": environment["TRAEFIK_HTTP2HTTPS"] == "True",
        "lets_encrypt": environment["TRAEFIK_LETS_ENCRYPT"] == "True",
    },
)
agent.assert_exp(
    configure_retval["exit_code"] == 0, "The configure-module subtask failed!"
)
